### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [KeenS/cargo-pack-docker#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by KeenS** [comment]
done in https://github.com/KeenS/cargo-pack-docker/commit/1ea66e5659460808fe5d66bac011235c43857d27
